import './globals.css'
import type { Metadata } from 'next'
import { Kumbh_Sans } from 'next/font/google'

const kumbhSans = Kumbh_Sans({ subsets: ['latin'], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${kumbhSans.className} bg-gradient-to-t from-blue to-voilet min-h-screen flex items-center justify-center p-8 md:px-20`}>{children}</body>
    </html>
  )
}
